/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal app setups. It is checked in here so
// TypeScript has the expected ambient types before the first local dev run.

