AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
AUTH_REQUIRED = "AUTH_REQUIRED"
AUTH_FORBIDDEN = "AUTH_FORBIDDEN"
AUTH_REFRESH_INVALID = "AUTH_REFRESH_INVALID"
AUTH_EMAIL_EXISTS = "AUTH_EMAIL_EXISTS"
RIOT_API_ERROR = "RIOT_API_ERROR"
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
VALIDATION_ERROR = "VALIDATION_ERROR"

